# Site settings
title: Tim R Peterson
email: hi@timrpeterson.com
description: > # this means to ignore newlines until "baseurl:"
  Tim R Peterson Lab. CRISPR, Javascript, Python, Golang, Aging, Osteoporosis, Mental Health, Circadian Rhythms, genomics, metabolomics, systems biology, computational biology, biomedical engineering, chemical biology, Bisphosphonates, SSRIs, Lithium, microfluidics, materials science, computer science, point of care diagnostics, quantified self, personalized medicine.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://timrpeterson.com" # the base hostname & protocol for your site
twitter_username: timrpeterson
github_username:  tim-peterson
linkedin_username:  petersontimr



# Build settings
markdown: kramdown

gems: ['jekyll-sitemap']
